### ISSUE TITLE
Render Rmd daily

### ISSUE THREAD

**Issue by judith-bourque** [judith-bourque/render-daily#1]
# 1. Setup
In R:
```
usethis::use_readme_rmd()
usethis::use_github_action("render-rmarkdown")

# Initialise renv
# github action depends on this
renv::init()
```

- [x] Create initial render of document
- [ ]  Activate read-write permission for GitHub Actions in the repository settings

<img width="774" alt="Screenshot 2023-04-21 at 11 58 14 AM" src="https://user-images.githubusercontent.com/59173478/233681913-d250a956-1316-477d-ba91-4fd10d67f041.png">

# 2. Set on schedule

- [ ] Replace `render-rmarkdown.yaml` with `render-readme.yaml`
```
# Workflow derived from https://github.com/r-lib/actions/tree/v2/examples
# Need help debugging build failures? Start at https://github.com/r-lib/actions#where-to-find-help
on:
  push:
    paths: ['README.Rmd']
  schedule:
    - cron: '0 * * * *'

name: render-rmarkdown

jobs:
  render-rmarkdown:
    runs-on: ubuntu-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3
        with:
          fetch-depth: 0

      - uses: r-lib/actions/setup-pandoc@v2

      - uses: r-lib/actions/setup-r@v2

      - uses: r-lib/actions/setup-renv@v2
      
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      
      - name: Commit Results
        run: |
          git config --local user.name "$GITHUB_ACTOR"
          git config --local user.email "$GITHUB_ACTOR@users.noreply.github.com"
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
```
See also: `schedule` [documentation](https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule)

**Comment by judith-bourque** [comment]
Couldn't commit

See [error message](https://github.com/judith-bourque/render-daily/actions/runs/4766564763/jobs/8473738749#step:6:49)

**Comment by judith-bourque** [comment]
Seems to need to activate read-write permission for GitHub Actions.

- [x] Activate read-write permission for GitHub Actions in the repository settings

<img width="774" alt="Screenshot 2023-04-21 at 11 58 14 AM" src="https://user-images.githubusercontent.com/59173478/233681913-d250a956-1316-477d-ba91-4fd10d67f041.png">

**Comment by judith-bourque** [comment]
The GitHub Action seems to only overwrite files known to git. (See [error](https://github.com/judith-bourque/render-daily/actions/runs/4766727850/jobs/8474110041#step:6:34))

- [x] Create initial render of document

**Comment by judith-bourque** [comment]
The basic workflow works.

- [x] Update workflow to run on schedule

**Comment by judith-bourque** [comment]
Tried every fifth minutes, syntax valid according to https://crontab.guru/, but doesn't work.

Code used:

```
on:
  schedule:
  # Run every fifth minute
    - cron:  '*/5 * * * *'
```

Ah wait, it does! Woo! Wait, no, it only works with original code.

- [ ] Run script daily

**Comment by judith-bourque** [comment]
I changed the workflow before it was done, might have caused [this error](https://github.com/judith-bourque/render-daily/actions/runs/4766989895/jobs/8474696512#step:6:1)

**Comment by judith-bourque** [comment]
Could be because I don't specify the path.

[YAML validator](https://www.yamllint.com/) suggests:
```
on:
  schedule:
    - cron: 40 * * * *
      paths:
        - "**.Rmd"
```

`Use the paths filter when you want to include file path patterns or when you want to both include and exclude file path patterns.` ([source](https://docs.github.com/en/actions/using-workflows/workflow-syntax-for-github-actions))

Path is used here:
https://github.com/judith-bourque/render-daily/blob/03a385c33ce1808bc40bfd67791833887b864ece/.github/workflows/render-rmarkdown.yaml#L28-L33

See also

- [Filter pattern cheatsheet](https://github.com/judith-bourque/render-daily/blob/03a385c33ce1808bc40bfd67791833887b864ece/.github/workflows/render-rmarkdown.yaml#L28-L33)
- [Learn YAML in 5 min](https://learnxinyminutes.com/docs/yaml/)
- [YAML validator](https://www.yamllint.com/)

**Comment by judith-bourque** [comment]
This didn't work

https://github.com/judith-bourque/render-daily/blob/833d08b9db787bbe2da91f9e23c35cc6a47aaa6b/.github/workflows/render-rmarkdown.yaml#L3-L7

**Comment by judith-bourque** [comment]
Trying square brackets
https://github.com/judith-bourque/render-daily/blob/eaa6452ac6f261d3259280a620825cf85b4f7008/.github/workflows/render-rmarkdown.yaml#L3-L6

**Comment by judith-bourque** [comment]
The code itself of the GitHub Actions needs rewriting. It seems to only re-render if there was a modified .Rmd in the last commit:
https://github.com/judith-bourque/render-daily/blob/eaa6452ac6f261d3259280a620825cf85b4f7008/.github/workflows/render-rmarkdown.yaml#L29


Paths isn't a valid element for on:schedule.

- [x] Remove Path
- [ ] Update workflow to re-knit all .Rmd

**Comment by judith-bourque** [comment]
Check out [bookdown workflow](https://github.com/r-lib/actions/blob/31167ece9439548766bdcc1aaf44394564ed8c86/examples/bookdown.yaml#L38-L40) for inspiration

`rmarkdown::render("test.Rmd")`

**Comment by judith-bourque** [comment]
[This presentation](https://bbest.github.io/gh-actions-demo/#20) recommends:

```
on:
  push:                
  schedule:            
    - cron: '0 * * * *'
```

Detailed explanation [here](https://www.jeffgeerling.com/blog/2020/running-github-actions-workflow-on-schedule-and-other-events) for

```
on:
  push:
  pull_request:
  schedule:
    - cron: '*/15 * * * *'
```

"The above would run the GitHub Actions workflow on every push (to any branch), every pull request (against any branch), and on the cron schedule of every 15 minutes through the day. I typically run my schedules either daily or weekly, depending on how much I need to track the day-to-day changes in my project's underlying dependencies."

**Comment by judith-bourque** [comment]
Example for [readme](https://www.rostrum.blog/2021/04/14/gha-readme/) here:

```
name: Render README

on:
  schedule:
    - cron: '09 05 * * *'

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install CRAN packages
        run: Rscript -e 'install.packages(c("remotes", "rmarkdown", "knitr", "tidyverse"))'
      - name: Install GitHub packages
        run: Rscript -e 'remotes::install_github("hadley/emo")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd")'
      - name: Commit results
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          git commit README.md README_files/ -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
```

**Comment by judith-bourque** [comment]
A simpler example [here](https://www.etiennebacher.com/posts/2021-03-19-use-github-actions-with-r-markdown-and-distill/):

```
on:
  push:
    branches: master
  schedule:
    - cron: '0 0 * * MON'

name: Render README

jobs:
  render:
    name: Render README
    runs-on: macOS-latest
    steps:
      - uses: actions/checkout@v2
      - uses: r-lib/actions/setup-r@v1
      - uses: r-lib/actions/setup-pandoc@v1
      - name: Install rmarkdown
        run: Rscript -e 'install.packages("rmarkdown")'
      - name: Render README
        run: Rscript -e 'rmarkdown::render("README.Rmd", output_format = "md_document")'
      - name: Commit results
        run: |
          git commit README.md -m 'Re-build README.Rmd' || echo "No changes to commit"
          git push origin || echo "No changes to commit"
```
